name: Build and Sign APK

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0, v2.0, etc.)
  workflow_dispatch:  # Allow manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # Step 2: Set up JDK
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # Step 3: Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Step 4: Sign APK
      - name: Sign APK
        run: |
          cd app/build/outputs/apk/release
          jarsigner -verbose -keystore ${{ secrets.KEYSTORE_PATH }} -storepass ${{ secrets.KEYSTORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} app-release-unsigned.apk ${{ secrets.KEY_ALIAS }}
          zipalign -v 4 app-release-unsigned.apk app-release.apk

      # Step 5: Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: MyAppRelease
          path: app/build/outputs/apk/release/app-release.apk
