name: Build and Sign APK

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (v1.0, v2.0, etc.)
  workflow_dispatch:  # Allow manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Ensure '17' matches the version you're using

      # Step 3: Grant execute permission for gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 4: Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Step 5: Sign APK
      - name: Sign app APK
        id: sign_app
        run: |
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore ${{ secrets.KEY_STORE }} \
            -storepass ${{ secrets.KEY_STORE_PASS }} \
            -keypass ${{ secrets.KEY_STORE_PASS }} \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            ${{ secrets.KEY_STORE_ALIAS }}

      # Step 6: Verify APK signature
      - name: Verify APK signature
        run: jarsigner -verify -verbose -certs app/build/outputs/apk/release/app-release-unsigned.apk

      # Step 7: Zipalign APK (optional but recommended)
      - name: Zipalign APK
        run: zipalign -v 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release-signed.apk

      # Step 8: Upload Signed APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: app/build/outputs/apk/release/app-release-signed.apk
